### ISSUE TITLE
Module install string appears twice with different versions in zef log 

### ISSUE THREAD

**Issue by melezhik** [lizmat/String-Fields#1]
Hi Liz. I am not sure if it is a module specific  issue,  or whether it is an issue by itself, but `Installing: String::Fields:ver<0.0.version>` appears twice with different versions during `zef install`. Please see details here - http://repo.westus.cloudapp.azure.com/rakudist/reports/String%3A%3AFields/debian/1579967617.txt

**Comment by lizmat** [comment]
Feels to me this is a bug in zef's module parsing?  I did update the module a few times in rather quick succession, so maybe that's the reason ?   There's really *nothing* special about that module.

**Comment by melezhik** [comment]
It could be. Worth to show to Nick Logan?

**Comment by lizmat** [comment]
Actually, there was, but in META6.json.  Somehow I had build dependency in there that shouldn't.  Fixed it now, new version on its way to CPAN now.  Thanks for the headsup!
